### ISSUE TITLE
validate of extensions doesn't seem to work

### ISSUE THREAD

**Issue by gmabey** [gnuradio/SigMF#186]
Either I made a mistake in implementing `core:extensions` or there's a problem validating it.  I added such an entry to `logo/sigmf_logo.sigmf-meta` 
```
{
    "global": {
        "core:author": "Kyle Logue, K6OF",
        "core:datatype": "ri16_le",
        "core:description": "The Official SigMF Logo",
        "core:license": "https://creativecommons.org/licenses/by-sa/4.0/",
        "core:num_channels": 2,
        "core:recorder": "OsciStudio & Audacity",
        "core:sample_rate": 48000,
        "core:sha512": "69893900f22de266485031b584c28fc3a0d4f361acd1d623698ed258e616e082d3d398af40d2ce805a804864cb0be631dba060f7410a27c0c2e497becdca53bf",
        "core:version": "1.0.0",
        "core:extensions": [
            {
                "name": "capture_details",
                "version": "1.0.0",
                "optional": false
            }
        ]
    },
    "captures": [
        {
            "core:datetime": "2021-06-18T23:17:51.163959Z",
            "core:sample_start": 0
        }
    ],
    "annotations": [
        {
            "core:comment": "logo warmup",
            "core:freq_lower_edge": -22000.0,
            "core:freq_upper_edge": 22000.0,
            "core:sample_count": 42000,
            "core:sample_start": 6000
        },
        {
            "core:comment": "logo spinup",
            "core:freq_lower_edge": -22000.0,
            "core:freq_upper_edge": 22000.0,
            "core:sample_count": 138000,
            "core:sample_start": 48000
        },
        {
            "core:comment": "logo steady",
            "core:freq_lower_edge": -22000.0,
            "core:freq_upper_edge": 22000.0,
            "core:sample_count": 96000,
            "core:sample_start": 186000
        }
    ]
}
```
and this is what I see:
```
[root@6c37442078e7 s]# /usr/local/python3_embedded/bin/sigmf_validate logo/sigmf_logo.sigmf-meta 
Traceback (most recent call last):
  File "/usr/local/python3_embedded/bin/sigmf_validate", line 33, in <module>
    sys.exit(load_entry_point('SigMF==0.0.2', 'console_scripts', 'sigmf_validate')())
  File "/usr/local/python3_embedded/lib/python3.9/site-packages/sigmf/validate.py", line 195, in main
    result = signal.validate()
  File "/usr/local/python3_embedded/lib/python3.9/site-packages/sigmf/sigmffile.py", line 320, in validate
    return validate.validate(
  File "/usr/local/python3_embedded/lib/python3.9/site-packages/sigmf/validate.py", line 154, in validate
    for result in (validate_section(data.get(key), ref.get(key), key) for key in ref):
  File "/usr/local/python3_embedded/lib/python3.9/site-packages/sigmf/validate.py", line 154, in <genexpr>
    for result in (validate_section(data.get(key), ref.get(key), key) for key in ref):
  File "/usr/local/python3_embedded/lib/python3.9/site-packages/sigmf/validate.py", line 145, in validate_section
    return {
  File "/usr/local/python3_embedded/lib/python3.9/site-packages/sigmf/validate.py", line 108, in validate_section_dict
    for result in key_validation_results:
  File "/usr/local/python3_embedded/lib/python3.9/site-packages/sigmf/validate.py", line 102, in <genexpr>
    validate_key(
  File "/usr/local/python3_embedded/lib/python3.9/site-packages/sigmf/validate.py", line 78, in validate_key
    if 'type' in ref_dict and not match_type(data_value, ref_dict["type"]):
  File "/usr/local/python3_embedded/lib/python3.9/site-packages/sigmf/validate.py", line 46, in match_type
    return value is None or {
KeyError: 'dict_list'
```

**Comment by bhilburn** [comment]
@Teque5 - Any chance you can poke your colleague for us? 😄

**Comment by Teque5** [comment]
Yea he told me today he's going to work on it. ¯\_(ツ)_/¯

**Comment by gmabey** [comment]
@Teque5 does your colleague have a name? :-D

**Comment by Teque5** [comment]
I sent him a chat now but I don't have any status update.

**Comment by gmabey** [comment]
@Teque5 proxy poke
